package jp.co.xing.karaokejoysound.ui.karaoke.gles.util
import android.opengl.GLES32
enum class DataType(val v:Int) {
    BYTE(GLES32.GL_BYTE),
    UNSIGNED_BYTE(GLES32.GL_UNSIGNED_BYTE),
    SHORT(GLES32.GL_SHORT),
    UNSIGNED_SHORT(GLES32.GL_UNSIGNED_SHORT),
    INT(GLES32.GL_INT),
    UNSIGNED_INT(GLES32.GL_UNSIGNED_INT),
    HALF_FLOAT(GLES32.GL_HALF_FLOAT),
    FLOAT(GLES32.GL_FLOAT),
    FIXED(GLES32.GL_FIXED),
    INT_2_10_10_10_REV(GLES32.GL_INT_2_10_10_10_REV),
    UNSIGNED_INT_2_10_10_10_REV(GLES32.GL_UNSIGNED_INT_2_10_10_10_REV)
}